.\"-
.\" Copyright (c) 2008 Anthony Wong <ypwong@debian.org>
.\" Copyrgith (c) 2015-2023 Abel Cheung <abelcheung@gmail.com>
.\"
.\" rifiuti2 is released under Revised BSD License.

.TH "rifiuti2" "1" "Nov 2023" "0.7.0" "MS Windows recycle bin analysis tool"

.SH NAME
rifiuti2 \[em] MS Windows recycle bin analysis tool

.SH SYNOPSIS
.na
.B "\fCrifiuti\/\fP \fRor\/\fP \fCrifiuti-vista\/\fP"
.B "[\-h | \-v | \-\-help | \-\-version]"
.br
.B "\fCrifiuti\/\fP [\-x | [\-n] [\-t \fIdelim\/\fP]] [\-z]"
.B "[\-l \fIcodepage\/\fP] [\-o \fIoutfile\/\fP] [\-\-] \fIinfo2_file\/\fP"
.br
.B "\fCrifiuti-vista\/\fP [\-x | [\-n] [\-t \fIdelim\/\fP]] [\-z]"
.B "[\-o \fIoutfile\/\fP] [\-\-] \fIinfo2_or_dir\/\fP"
.br
.B "\fCrifiuti-vista\/\fP --live [\-x | [\-n] [\-t \fIdelim\/\fP]]"
.B "[\-z] [\-o \fIoutfile\/\fP]"
.ad n

.SH DESCRIPTION
.nr PI 2n
This manpage is now obsolete. Please read REAMDE and Wiki
from online repository for more information.
.IP \[bu]
https://github.com/abelcheung/rifiuti2/
.IP \[bu]
https://github.com/abelcheung/rifiuti2/wiki/

.SH COPYRIGHT
rifiuti2 is released under Revised BSD license.

.SH AUTHOR
The main author is Abel Cheung
.nh
\fC<abelcheung@gmail.com>\fP
.hy
.PP
The original author of rifiuti is Keith J. Jones
.nh
\fC<keith.jones@foundstone.com>\fP
.hy
.PP
Anthony Wong
.nh
\fC<ypwong@debian.org>\fP
.hy
helped in Debian packaging and was author of the original manpage.
